"""Evidence and Finding types, plus the citation index.

Everything the AI layer is allowed to say has to come from here. Findings and
their citations are generated by deterministic code *before* the model is called,
so the model selects from a fixed set rather than recalling identifiers -- it
cannot introduce a correlation ID because none of its inputs contain an
unreferenced one.

The citation index is what makes that enforceable rather than aspirational: any
hypothesis citing a ref absent from the index is dropped in validator.py.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Literal

Severity = Literal["critical", "high", "medium", "low"]
Confidence = Literal["observed", "inferred", "ambiguous"]

SEVERITY_ORDER: dict[str, int] = {"critical": 4, "high": 3, "medium": 2, "low": 1}
EvidenceKind = Literal["correlation_id", "trace_id", "span", "log", "deploy", "metric"]


@dataclass(frozen=True)
class Evidence:
    kind: EvidenceKind
    ref: str
    """The citable identifier. This is what a hypothesis must reference."""

    detail: str
    """Human-readable and pre-rendered, so the model never formats a number."""

    source: str
    """Where to look to check it by hand, e.g. spans.json#span_id=00000000000a744a"""

    def as_dict(self) -> dict:
        return {
            "kind": self.kind,
            "ref": self.ref,
            "detail": self.detail,
            "source": self.source,
        }


@dataclass(frozen=True)
class Hypothesis:
    """A competing explanation the tool is forbidden from collapsing away."""

    id: str
    summary: str
    supports: list[str] = field(default_factory=list)
    against: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {
            "id": self.id,
            "summary": self.summary,
            "supports": list(self.supports),
            "against": list(self.against),
        }


@dataclass
class Finding:
    id: str
    title: str
    severity: Severity
    confidence: Confidence
    summary: str
    evidence: list[Evidence] = field(default_factory=list)
    affected: list[str] = field(default_factory=list)
    alternatives: list[Hypothesis] = field(default_factory=list)
    would_resolve: list[str] = field(default_factory=list)
    params: dict[str, object] = field(default_factory=dict)
    """Thresholds this finding depended on, printed so they are never implicit."""

    low_confidence_rate: bool = False
    """True when a rate was computed below min_samples and must be read as a count."""

    @property
    def affected_count(self) -> int:
        return len(self.affected)

    def exemplars(self, limit: int = 5) -> list[str]:
        return self.affected[:limit]

    @property
    def rank_score(self) -> tuple[int, int]:
        """Ranking is code-owned. The model cannot promote a guess by asserting
        certainty about it.

        Severity is primary and support count only breaks ties. A plain product
        (severity x support) lets a well-evidenced medium outrank a thinly
        evidenced high, which is precisely the misprioritisation this tool exists
        to prevent -- a 100% channel loss with two citations still outranks a
        tidy log-hygiene finding with six.
        """
        return (SEVERITY_ORDER.get(self.severity, 0), len(self.evidence))

    def as_dict(self, exemplar_limit: int = 5) -> dict:
        payload = {
            "finding_id": self.id,
            "title": self.title,
            "severity": self.severity,
            "confidence": self.confidence,
            "summary": self.summary,
            "affected_count": self.affected_count,
            "exemplars": self.exemplars(exemplar_limit),
            "evidence": [e.as_dict() for e in self.evidence],
        }
        if self.alternatives:
            payload["alternatives"] = [h.as_dict() for h in self.alternatives]
        if self.would_resolve:
            payload["would_resolve"] = list(self.would_resolve)
        if self.params:
            payload["params"] = dict(self.params)
        if self.low_confidence_rate:
            payload["rate_confidence"] = "low — sample below min_samples, read as a count"
        return payload


class CitationIndex:
    """Every ref any finding cited. A hypothesis may cite nothing else."""

    def __init__(self) -> None:
        self._refs: dict[str, Evidence] = {}
        self._finding_ids: set[str] = set()

    def add_findings(self, findings: Iterable[Finding]) -> None:
        for finding in findings:
            self._finding_ids.add(finding.id)
            for item in finding.evidence:
                self._refs.setdefault(item.ref, item)
            for correlation_id in finding.affected:
                self._refs.setdefault(
                    correlation_id,
                    Evidence(
                        kind="correlation_id",
                        ref=correlation_id,
                        detail=f"affected by {finding.id}",
                        source="accepted_messages.json",
                    ),
                )

    def knows(self, ref: str) -> bool:
        return ref in self._refs or ref in self._finding_ids

    def get(self, ref: str) -> Evidence | None:
        return self._refs.get(ref)

    @property
    def refs(self) -> set[str]:
        return set(self._refs) | set(self._finding_ids)

    def __len__(self) -> int:
        return len(self.refs)


@dataclass
class EvidenceBundle:
    """Everything the model is given. Size is O(findings), not O(telemetry).

    A 10x traffic increase must not change the size of this object -- that is the
    single property that lets the AI layer survive go-live unchanged.
    """

    complaint: str
    findings: list[Finding]
    summary: dict
    deploys: list[dict]
    index: CitationIndex = field(default_factory=CitationIndex)

    def __post_init__(self) -> None:
        self.index.add_findings(self.findings)

    def ranked(self) -> list[Finding]:
        return sorted(self.findings, key=lambda f: f.rank_score, reverse=True)

    def by_id(self, finding_id: str) -> Finding | None:
        return next((f for f in self.findings if f.id == finding_id), None)

    def as_prompt_payload(self, exemplar_limit: int = 5) -> dict:
        return {
            "pipeline_summary": self.summary,
            "deploys": self.deploys,
            "findings": [f.as_dict(exemplar_limit) for f in self.ranked()],
        }
